# Generated by Django 5.1.1 on 2025-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.CharField(default='/img/image1.PNG', max_length=255),
        ),
    ]
