# Generated by Django 5.1.1 on 2025-03-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_user_balance_user_birthday_user_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.FloatField(),
        ),
    ]
