# Generated by Django 5.1.1 on 2025-03-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_book_is_overdue'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('Book Club', 'Book Club'), ('Author Talk', 'Author Talk'), ('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Other', 'Other')], default='Other', max_length=50)),
                ('poster', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='pages.book')),
            ],
        ),
    ]
