# Generated by Django 5.1.1 on 2025-03-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_libraryevent_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryevent',
            name='location',
            field=models.CharField(default='Main Library', max_length=255),
        ),
    ]
