# Generated by Django 5.1.1 on 2025-03-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_libraryevent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryevent',
            name='poster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
