# Generated by Django 5.1.1 on 2025-03-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_libraryevent_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.CharField(default='/img/book.jpg', max_length=255),
        ),
    ]
